<?php

namespace AdminBundle\Repository;

/**
 * EntitiesFetchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitiesFetchRepository extends \Doctrine\ORM\EntityRepository
{
}
