services:
    api.user:
        class: APIBundle\Service\user
        arguments: [ "@doctrine.orm.entity_manager", "@buzz"]

    api.session:
        class: APIBundle\Service\session
        arguments: [ "@doctrine.orm.entity_manager", "@buzz", "@api.log", "@entity.process"]

    api.proposal_browse:
        class: APIBundle\Service\proposalBrowse
        arguments: [ "@doctrine.orm.entity_manager", "@buzz", "@api.proposal_browse_item"]

    api.proposal_browse_item:
        class: APIBundle\Service\proposalBrowseItem
        arguments: [ "@doctrine.orm.entity_manager", "@buzz"]

    api.proposal_single:
        class: APIBundle\Service\proposalSingle
        arguments: [ "@doctrine.orm.entity_manager", "@buzz", "@api.session"]

    api.log:
        class: APIBundle\Service\log
        arguments: [ "@doctrine.orm.entity_manager"]

    api.context:
        class: APIBundle\Service\context
        arguments: [ "@doctrine.orm.entity_manager", "@buzz", "@api.log", "@entity.graph", "@api.proposal_single", "@api.proposal_browse", "@api.proposal_browse_item"]

