# System
messenger_system_restart:
    path:     /system/restart
    defaults: { _controller: MessengerBundle:System:restart }

# User
messenger_user_index:
    path:     /user/{authToken}/{user_id}/{user_locale}/{user_ref}/{user_timezone}
    defaults: { _controller: MessengerBundle:User:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        user_id: \S{0,255}
        user_locale: \S{0,255}
        user_ref: \S{0,255}
        user_timezone: \S{0,255}

messenger_user_load:
    path:     /user/{authToken}/{experiment_user_id}
    defaults: { _controller: MessengerBundle:User:load }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_user_id: \d+

# Session
messenger_session_index:
    path:     /session/{authToken}/{experiment_user_id}
    defaults: { _controller: MessengerBundle:Session:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_user_id: \d+

messenger_session_close:
    path:     /session/close/{authToken}/{experiment_session_id}
    defaults: { _controller: MessengerBundle:Session:close }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_session_id: \d+

# Proposal
messenger_proposal_index:
    path:     /proposal/{authToken}/{experiment_session_id}
    defaults: { _controller: MessengerBundle:Proposal:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_session_id: \d+

# ProposalSingle
messenger_proposal_single_index:
    path:     /proposal/single/{authToken}/{experiment_proposal_single_id}
    defaults: { _controller: MessengerBundle:ProposalSingle:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_proposal_single_id: \d+

messenger_proposal_single_validation:
    path:     /proposal/single/validation/{authToken}/{experiment_proposal_single_id}/{value}
    defaults: { _controller: MessengerBundle:ProposalSingle:validation }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_proposal_single_id: \d+
        value: \d+

# ProposalBrowse
messenger_proposal_browse_index:
    path:     /proposal/browse/{authToken}/{experiment_proposal_browse_id}
    defaults: { _controller: MessengerBundle:ProposalBrowse:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_proposal_browse_id: \d+

messenger_proposal_browse_validation:
    path:     /proposal/browse/validation/{authToken}/{experiment_proposal_browse_id}/{experiment_proposal_browse_i_id}
    defaults: { _controller: MessengerBundle:ProposalBrowse:validation }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_proposal_browse_id: \d+
        experiment_proposal_browse_i_id: \d+


