# System
messenger_system_restart:
    path:     /system/restart
    defaults: { _controller: MessengerBundle:System:restart }

# Session
messenger_session_index:
    path:     /session/{authToken}/{user_id}/{user_locale}/{user_ref}/{user_timezone}
    defaults: { _controller: MessengerBundle:Session:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        user_id: \S{0,255}
        user_locale: \S{0,255}
        user_ref: \S{0,255}
        user_timezone: \S{0,255}

messenger_session_load:
    path:     /session/{authToken}/{experiment_session_id}
    defaults: { _controller: MessengerBundle:Session:load }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_session_id: \d+

# Sequence
messenger_sequence_index:
    path:     /sequence/{authToken}/{experiment_session_id}
    defaults: { _controller: MessengerBundle:Sequence:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_session_id: \d+

# Proposal
messenger_proposal_index:
    path:     /proposal/{authToken}/{experiment_sequence_id}
    defaults: { _controller: MessengerBundle:Proposal:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_sequence_id: \d+

# ProposalSingle
messenger_proposal_single_index:
    path:     /proposal/single/{authToken}/{experiment_proposal_single_id}
    defaults: { _controller: MessengerBundle:ProposalSingle:index }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_proposal_single_id: \d+

messenger_proposal_single_validation:
    path:     /proposal/single/validation/{authToken}/{experiment_proposal_single_id}/{value}
    defaults: { _controller: MessengerBundle:ProposalSingle:validation }
    requirements:
        authToken: "8u0QYy8OTLVKZK8"
        experiment_proposal_single_id: \d+
        value: \d+


