<?php

namespace APIBundle\Repository;

/**
 * EvaluationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationUserRepository extends \Doctrine\ORM\EntityRepository
{
}
