<?php

namespace APIBundle\Repository;

/**
 * EvaluationSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
