<?php

namespace APIBundle\Repository;

/**
 * EvaluationProposalBrowseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationProposalBrowseRepository extends \Doctrine\ORM\EntityRepository
{
}
