<?php

namespace APIBundle\Repository;

/**
 * EvaluationProposalSingleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationProposalSingleRepository extends \Doctrine\ORM\EntityRepository
{
}
