<?php

namespace APIBundle\Repository;

/**
 * EvaluationProposalBrowseItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationProposalBrowseItemRepository extends \Doctrine\ORM\EntityRepository
{
}
