<?php

namespace APIBundle\Repository;

/**
 * EvaluationSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationSessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReferenceItems($user)
    {
        $qb = $this->createQueryBuilder('s');

        $qb ->where('s.user = :user')
            ->andWhere($qb->expr()->isNotNull('s.referenceItem'))
            ->setParameter('user', $user);

        return $qb->getQuery()
                  ->getResult();
    }
}
