<?php

namespace APIBundle\Repository;

/**
 * EvaluationSequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationSequenceRepository extends \Doctrine\ORM\EntityRepository
{
}
