<?php

namespace EntityBundle\Repository;

/**
 * EntityRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRelationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnusedEntity($ids)
    {
        $qb = $this->createQueryBuilder('e');

        $qb ->where($qb->expr()->notIn('entity1', $ids));

        return $qb->getQuery()
            ->getResult();
    }
}
