<?php

namespace EntityBundle\Repository;

/**
 * EntityPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityPropertyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnusedEntity($ids)
    {
        $qb = $this->createQueryBuilder('e');

        $qb ->where($qb->expr()->notIn('europeanaId', $ids));

        return $qb->getQuery()
                  ->getResult();
    }

    public function getAll()
    {
        $qb = $this->createQueryBuilder('e');

        $qb ->select('e.europeanaId')
            ->distinct();

        return $qb->getQuery()
                  ->getResult();
    }
}
