<?php

namespace EntityBundle\Repository;

/**
 * EntityFetchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityFetchRepository extends \Doctrine\ORM\EntityRepository
{
}
